name: CI
run-name: ${{ github.ref_name }} CI ✅

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test 🧪
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: $/.github/actions/probe-local
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Set Up Node 🟢
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '20'

      - name: Enable Corepack 📦
        run: corepack enable

      - name: Install Dependencies 📦
        run: npm install

      - name: Run Tests ✅
        run: npm test
